# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matt Chan
tagline:          'Thoughts and Experiments'
description:      'A place to put what I am thinking about or working on'
url:              http://mattchan.org
baseurl:          /

author:
  name:           'Matthew Chan'
  url:            https://twitter.com/mattam

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattam/mattam.github.com
