# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matt Chan
tagline:          'Thoughts and Experiments'
description:      'A place for my thoughts and experiments'
url:              http://mattchan.org
baseurl:          /

author:
  name:           'Matthew Chan'
  url:            https://twitter.com/mattam

paginate:         1

# Custom vars

github:
  repo:           https://github.com/mattam/mattam.github.com
